DELIMITER;

CREATE OR REPLACE VIEW `view_job_calculation_to_report` AS
select
    `p`.`use_in_offer` AS `use_row`,
    
    `p`.`use_real_amount` AS `use_real_amount`,

    `h`.`approved` AS `approved`,
    `j`.`id` AS `jobid`,
    `g`.`langtext` AS `langtext`,
    `j`.`job_number` AS `job_number`,
    `h`.`document_name` AS `document_name`,
    `r`.`name` AS `reporting_type`,
    `w`.`warengruppe` AS `warengruppe`,
    `p`.`use_in_offer` AS `use_in_offer`,
    `p`.`beleg` AS `beleg`,
    `p`.`gruppierung` AS `gruppierung`,
    `p`.`artikel` AS `artikel`,
    `p`.`anzahl` AS `anzahl`,
    `p`.`ist_anzahl` AS `ist_anzahl`,
    `g`.`gruppe` AS `gruppe`,
    `p`.`vdatum` AS `vdatum`,
    `p`.`netto` AS `netto`,
    `p`.`epreis` AS `epreis`,
    `p`.`steuer` AS `steuer`,
    `p`.`brutto` AS `brutto`,
    `p`.`bemerkung` AS `bemerkung`,
    `p`.`pos` AS `position`,
    `p`.`steuersatz` AS `steuersatz`,
    `p`.`id` AS `id`,
    `p`.`leistungsbeschreibung` AS `leistungsbeschreibung`,
    `p`.`pos_text` AS `pos_text`,
    `p`.`gruppenpreis_netto` AS `gruppenpreis_netto`,
    `p`.`gruppenpreis_brutto` AS `gruppenpreis_brutto`,
    `p`.`gruppenmenge` AS `gruppenmenge`,
    `p`.`teilueberschrift` AS `teilueberschrift`
from
    (
        (
            (
                (
                    (
                        (
                            `tualo_job` `j`
                            join `blg_hdr_calculation` `h` on(
                                `j`.`order_date` > curdate() + interval -26 month
                                and `j`.`id` = `h`.`jobid`
                            )
                        )
                        join `blg_pos_calculation` `p` on(
                            `p`.`beleg` = `h`.`id`
                            and (
                                `p`.`zid` is null
                                or `p`.`zid` = 0
                            )
                            and (
                                `p`.`oid` is null
                                or `p`.`oid` = 0
                            )
                        )
                    )
                    join `artikelgruppen` `g` on(`g`.`gruppen_id` = `p`.`artikel`)
                )
                join `warengruppen` `w` on(`w`.`id` = `g`.`warengruppe`)
            )
            left join `type_of_service_reporting_service_type` `s` on(`s`.`type_of_service_link` = `g`.`gruppen_id`)
        )
        left join `reporting_service_type` `r` on(`r`.`id` = `s`.`reporting_service_type`)
    );


SET FOREIGN_KEY_CHECKS=0;
INSERT INTO `ds` (`allowform`,`autosave`,`base_store_class`,`class_name`,`combined`,`default_pagesize`,`displayfield`,`existsreal`,`globalsearch`,`listselectionmodel`,`listviewbaseclass`,`modelbaseclass`,`phpexporter`,`phpexporterfilename`,`reorderfield`,`searchany`,`searchfield`,`showactionbtn`,`sortdirection`,`sortfield`,`syncable`,`table_name`,`title`,`use_history`,`use_insert_for_update`,`writetable`) VALUES ('0','0','Tualo.DataSets.data.Store','ProAd-Tualo-Ersatz','0','1000','jobid','1','0','cellmodel','Tualo.DataSets.ListView','Tualo.DataSets.model.Basic','XlsxWriter','view_job_calculation_to_report {DATE} {TIME}','position','0','jobid','1','ASC','position','0','view_job_calculation_to_report','Kalkulation zu Angebot','0','0','blg_pos_calculation') ON DUPLICATE KEY UPDATE `allowform`=values(`allowform`),`autosave`=values(`autosave`),`base_store_class`=values(`base_store_class`),`class_name`=values(`class_name`),`combined`=values(`combined`),`default_pagesize`=values(`default_pagesize`),`displayfield`=values(`displayfield`),`existsreal`=values(`existsreal`),`globalsearch`=values(`globalsearch`),`listselectionmodel`=values(`listselectionmodel`),`listviewbaseclass`=values(`listviewbaseclass`),`modelbaseclass`=values(`modelbaseclass`),`phpexporter`=values(`phpexporter`),`phpexporterfilename`=values(`phpexporterfilename`),`reorderfield`=values(`reorderfield`),`searchany`=values(`searchany`),`searchfield`=values(`searchfield`),`showactionbtn`=values(`showactionbtn`),`sortdirection`=values(`sortdirection`),`sortfield`=values(`sortfield`),`syncable`=values(`syncable`),`table_name`=values(`table_name`),`title`=values(`title`),`use_history`=values(`use_history`),`use_insert_for_update`=values(`use_insert_for_update`),`writetable`=values(`writetable`); 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','anzahl','decimal(12,5)','decimal','0','0','0','1','','NEVER','NO','0','12','5','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('3','utf8mb4','','approved','varchar(3)','varchar','0','0','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('255','utf8mb4','','artikel','varchar(255)','varchar','0','0','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','beleg','bigint(20)','bigint','0','0','0','1','','NEVER','NO','0','19','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('4000','utf8mb4','','bemerkung','varchar(4000)','varchar','0','0','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','brutto','decimal(15,5)','decimal','0','0','0','1','','NEVER','YES','0','15','5','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('240','utf8mb4','','document_name','varchar(240)','varchar','0','0','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','epreis','decimal(12,5)','decimal','0','0','0','1','','NEVER','NO','0','12','5','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('255','utf8mb4','','gruppe','varchar(255)','varchar','0','0','0','1','','NEVER','NO','0','0','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','gruppenmenge','decimal(15,5)','decimal','0','0','0','1','','NEVER','YES','0','15','5','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','gruppenpreis_brutto','decimal(15,5)','decimal','0','0','0','1','','NEVER','YES','0','15','5','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','gruppenpreis_netto','decimal(15,5)','decimal','0','0','0','1','','NEVER','YES','0','15','5','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('255','utf8mb4','','gruppierung','varchar(255)','varchar','0','0','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','id','bigint(20)','bigint','0','0','0','1','','NEVER','NO','1','19','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('36','utf8mb4','','jobid','varchar(36)','varchar','0','0','0','1','','NEVER','NO','0','0','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('60','utf8mb4','','job_number','varchar(60)','varchar','0','0','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('255','utf8mb4','','langtext','varchar(255)','varchar','0','0','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('65535','utf8mb4','','leistungsbeschreibung','text','text','0','0','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','netto','decimal(15,5)','decimal','0','0','0','1','','NEVER','YES','0','15','5','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','position','int(11)','int','0','0','0','1','','NEVER','YES','0','10','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('20','utf8mb4','','pos_text','varchar(20)','varchar','0','0','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('255','utf8mb4','','reporting_type','varchar(255)','varchar','0','0','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','steuer','decimal(12,5)','decimal','0','0','0','1','','NEVER','NO','0','12','5','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','steuersatz','decimal(12,5)','decimal','0','0','0','1','','NEVER','NO','0','12','5','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('100','utf8mb4','','teilueberschrift','varchar(100)','varchar','0','0','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','use_in_offer','tinyint(4)','tinyint','0','0','0','1','','NEVER','YES','0','3','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','use_row','tinyint(4)','tinyint','0','0','0','1','','NEVER','YES','0','3','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','vdatum','date','date','0','0','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('100','utf8mb4','','warengruppe','varchar(100)','varchar','0','0','0','1','','NEVER','NO','0','0','0','select,insert,update,references','0','view_job_calculation_to_report','1') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','end','anzahl','{}','','','1','deValueRenderer','0','0','Anzahl','DE','','16','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','approved','{}','','','1','','0','1','genehmigt','DE','','2','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','artikel','{}','','','1','','0','0','Artikel','DE','','8','ds_artikelgruppen_gruppen_id_kurz','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','beleg','{}','','','1','','0','1','Beleg','DE','','5','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('0','start','bemerkung','{}','','','1','','0','1','bemerkung','DE','','999','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','brutto','{}','','','1','deValueRenderer','0','1','brutto','DE','','20','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','document_name','{}','','','1','','0','0','Kalk.-Name','DE','','6','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','end','epreis','{}','','','1','deValueRenderer5','0','0','Einzelpreis','DE','','17','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','gruppe','{}','','','1','','0','1','Bezeichnung','DE','','9','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','gruppenmenge','{}','','','1','deValueRenderer5','0','1','gruppenmenge','DE','','21','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','gruppenpreis_brutto','{}','','','1','deValueRenderer5','0','1','gruppenpreis_brutto','DE','','22','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','gruppenpreis_netto','{}','','','1','deValueRenderer5','0','1','gruppenpreis_netto','DE','','23','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','gruppierung','{}','','','1','','0','1','Gruppierung','DE','','7','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','id','{}','','','1','','0','1','Id','DE','','11','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','jobid','{}','','','1','','0','1','Job-Id','DE','','12','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','job_number','{}','','','1','','0','1','Job-Kurzname','DE','','4','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('0','start','langtext','{}','','','1','','0','1','langtext','DE','','999','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','leistungsbeschreibung','{}','textarea','','1','','0','0','Beschreibung','DE','','10','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','end','netto','{}','','','1','deValueRenderer5','0','0','Netto','DE','','18','','deColoredMoneyRenderer','sum','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','position','{}','','','1','','0','1','position','DE','','24','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','pos_text','{}','textfield','','1','','0','0','Position-Text','DE','','25','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','reporting_type','{}','','','1','','0','0','Typ','DE','','3','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','steuer','{}','','','1','','0','1','Steuer','DE','','13','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','steuersatz','{}','','','1','','0','1','Steuersatz','DE','','14','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','teilueberschrift','{}','textfield','','1','','0','0','Überschrift','DE','','26','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','use_in_offer','{}','','','1','','0','0','verwenden','DE','','1','','','','view_job_calculation_to_report','checkcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('0','start','use_row','{}','','','1','','0','1','verwenden','DE','','0','','','','view_job_calculation_to_report','checkcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','vdatum','{}','','','1','deDate','0','0','Zieldatum','DE','','19','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','start','warengruppe','{}','','','1','','0','1','Warengruppe','DE','','15','','','','view_job_calculation_to_report','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','anzahl','','Allgemein','1','1','anzahl','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','approved','','Allgemein','1','1','approved','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','artikel','','Allgemein','1','1','artikel','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','beleg','','Allgemein','1','1','beleg','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','bemerkung','','Allgemein','1','1','bemerkung','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','brutto','','Allgemein','1','1','brutto','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','document_name','','Allgemein','1','1','document_name','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','epreis','','Allgemein','1','1','epreis','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','gruppe','','Allgemein','1','1','gruppe','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','gruppenmenge','','Allgemein','1','1','gruppenmenge','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','gruppenpreis_brutto','','Allgemein','1','1','gruppenpreis_brutto','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','gruppenpreis_netto','','Allgemein','1','1','gruppenpreis_netto','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','gruppierung','','Allgemein','1','1','gruppierung','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','id','','Allgemein','1','1','id','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','jobid','','Allgemein','1','1','jobid','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','job_number','','Allgemein','1','1','job_number','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','langtext','','Allgemein','1','1','langtext','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','leistungsbeschreibung','','Allgemein','1','1','leistungsbeschreibung','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','netto','','Allgemein','1','1','netto','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','position','','Allgemein','1','1','position','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','pos_text','','Allgemein','1','1','pos_text','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','reporting_type','','Allgemein','1','1','reporting_type','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','steuer','','Allgemein','1','1','steuer','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','steuersatz','','Allgemein','1','1','steuersatz','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','teilueberschrift','','Allgemein','1','1','teilueberschrift','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','use_in_offer','','Allgemein','1','1','use_in_offer','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','use_row','','Allgemein','1','1','use_row','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','vdatum','','Allgemein','1','1','vdatum','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','warengruppe','','Allgemein','1','1','warengruppe','DE','999','view_job_calculation_to_report','displayfield') ; 
INSERT IGNORE INTO `ds_access` (`append`,`delete`,`read`,`role`,`table_name`,`write`) VALUES ('0','0','0','_default_','view_job_calculation_to_report','0') ; 
INSERT IGNORE INTO `ds_access` (`append`,`delete`,`read`,`role`,`table_name`,`write`) VALUES ('1','0','1','administration','view_job_calculation_to_report','1') ; 
REPLACE INTO `docsystem_ds` (`table_name`) VALUES ('view_job_calculation_to_report') ; 
SET FOREIGN_KEY_CHECKS=1;